# Stage 1: Build the Go application
FROM golang:1.23.2-alpine AS builder

WORKDIR /app

COPY ./expoter_go .
RUN go mod download

RUN go build -o exporter_go .

# Stage 2: Copy the Go application to a new image
FROM alpine:3.12

WORKDIR /app

COPY --from=builder /app/exporter_go .

CMD ["./exporter_go"]