global:
  scrape_interval: 25s

scrape_configs:
  - job_name: 'stress_test'
    metrics_path: /metrics
    scrape_timeout: 20s
    static_configs:
      - targets: ['synthetic-exporter-1:8000']
      - targets: ['synthetic-exporter-2:8000']
      - targets: ['synthetic-exporter-3:8000']
      - targets: ['synthetic-exporter-4:8000']
      - targets: ['synthetic-exporter-5:8000']
      - targets: ['synthetic-exporter-6:8000']
      - targets: ['synthetic-exporter-7:8000']
      - targets: ['synthetic-exporter-8:8000']
      - targets: ['synthetic-exporter-9:8000']
      - targets: ['synthetic-exporter-10:8000']
      - targets: ['synthetic-exporter-11:8000']
      - targets: ['synthetic-exporter-12:8000']
      - targets: ['synthetic-exporter-13:8000']
      - targets: ['synthetic-exporter-14:8000']
      - targets: ['synthetic-exporter-15:8000']
      - targets: ['synthetic-exporter-16:8000']
      - targets: ['synthetic-exporter-17:8000']
      - targets: ['synthetic-exporter-18:8000']
      - targets: ['synthetic-exporter-19:8000']
      - targets: ['synthetic-exporter-20:8000']
      - targets: ['synthetic-exporter-21:8000']
      - targets: ['synthetic-exporter-22:8000']
      - targets: ['synthetic-exporter-23:8000']
      - targets: ['synthetic-exporter-24:8000']
      - targets: ['synthetic-exporter-25:8000']
      - targets: ['synthetic-exporter-26:8000']
      - targets: ['synthetic-exporter-27:8000']
      - targets: ['synthetic-exporter-28:8000']
      - targets: ['synthetic-exporter-29:8000']
      - targets: ['synthetic-exporter-30:8000']
      - targets: ['synthetic-exporter-31:8000']
      - targets: ['synthetic-exporter-32:8000']
      - targets: ['synthetic-exporter-33:8000']
      - targets: ['synthetic-exporter-34:8000']
      - targets: ['synthetic-exporter-35:8000']
      - targets: ['synthetic-exporter-36:8000']
      - targets: ['synthetic-exporter-37:8000']
      - targets: ['synthetic-exporter-38:8000']
      - targets: ['synthetic-exporter-39:8000']
      - targets: ['synthetic-exporter-40:8000']
      - targets: ['synthetic-exporter-41:8000']
      - targets: ['synthetic-exporter-42:8000']
      - targets: ['synthetic-exporter-43:8000']
      - targets: ['synthetic-exporter-44:8000']
      - targets: ['synthetic-exporter-45:8000']
      - targets: ['synthetic-exporter-46:8000']
      - targets: ['synthetic-exporter-47:8000']
      - targets: ['synthetic-exporter-48:8000']
      - targets: ['synthetic-exporter-49:8000']
      - targets: ['synthetic-exporter-50:8000']
      - targets: ['synthetic-exporter-51:8000']
      - targets: ['synthetic-exporter-52:8000']
      - targets: ['synthetic-exporter-53:8000']
      - targets: ['synthetic-exporter-54:8000']
      - targets: ['synthetic-exporter-55:8000']
      - targets: ['synthetic-exporter-56:8000']
      - targets: ['synthetic-exporter-57:8000']
      - targets: ['synthetic-exporter-58:8000']
      - targets: ['synthetic-exporter-59:8000']
      - targets: ['synthetic-exporter-60:8000']
      - targets: ['synthetic-exporter-61:8000']
      - targets: ['synthetic-exporter-62:8000']
      - targets: ['synthetic-exporter-63:8000']
      - targets: ['synthetic-exporter-64:8000']
      - targets: ['synthetic-exporter-65:8000']
      - targets: ['synthetic-exporter-66:8000']
      - targets: ['synthetic-exporter-67:8000']
      - targets: ['synthetic-exporter-68:8000']
      - targets: ['synthetic-exporter-69:8000']
      - targets: ['synthetic-exporter-70:8000']
      - targets: ['synthetic-exporter-71:8000']
      - targets: ['synthetic-exporter-72:8000']
      - targets: ['synthetic-exporter-73:8000']
      - targets: ['synthetic-exporter-74:8000']
      - targets: ['synthetic-exporter-75:8000']
