all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/augusto/.ssh/ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    managers:
      hosts:
        manager-0:
          ansible_host: 201.23.0.248
          private_ip: 172.30.0.89
    workers:
      hosts:
        worker-0:
          ansible_host: 177.93.134.152
          private_ip: 172.30.0.96
        worker-1:
          ansible_host: 201.23.1.85
          private_ip: 172.30.0.98
